/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.PricingManagement;

import TheBusiness.Business.Business;
import TheBusiness.ProductManagement.Product;
import TheBusiness.ProductManagement.ProductCatalog;
import TheBusiness.ProductManagement.ProductSummary;
import TheBusiness.Supplier.Supplier;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 陈凯璐
 */
public class ManagePriceJPanel extends javax.swing.JPanel {
    JPanel CardSequencePanel; 
    Business business;
    Supplier selectedsupplier;
    Product selectedproduct;
   

    /**
     * Creates new form IdentifyEventTypes
     */
    public ManagePriceJPanel(Business b, JPanel clp) {
        initComponents();
        this.business = b;
        this.CardSequencePanel = clp;
        populateCombobox();
    }
    private void populateTable1(String suppliername) {
       DefaultTableModel model = (DefaultTableModel)SupplierCatalogTable.getModel();
       model.setRowCount(0);
       selectedsupplier = business.getSupplierDirectory().findSupplier(suppliername);
       ProductCatalog pc = selectedsupplier.getProductCatalog();
       for(  Product pt : pc.getProductList()){ 
           Object[] row = new Object[5];
            row[0] = pt;
            row[1] = pt.getTargetPrice();
            row[2] = pt.getProductSummary().getNumberAboveTarget();
            row[3] = pt.getProductSummary().getNumberBelowTarget();
            row[4] = pt.getProductSummary().getStatus();
          model.addRow(row);
        }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SuppliersComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SupplierCatalogTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbBelowTarget = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbAboveTarget = new javax.swing.JComboBox<>();
        btnRunSimulation = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRunSimulation = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtHighestImpactProduct = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotalRevenueChange = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setBackground(new java.awt.Color(0, 153, 153));

        SuppliersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppliersComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Suppliers");

        jLabel8.setText("Product");

        SupplierCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Target Price", "Freq Above Target", "Freq Below Target", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SupplierCatalogTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupplierCatalogTableMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SupplierCatalogTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(SupplierCatalogTable);

        jLabel2.setText("Decrease % for Below Target:");

        cmbBelowTarget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "20%", "30%", "40%", "50%" }));

        jLabel3.setText("Increase % for Above Target");

        cmbAboveTarget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "20%", "30%", "40%", "50%" }));

        btnRunSimulation.setText("Run Simulation");
        btnRunSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunSimulationActionPerformed(evt);
            }
        });

        tblRunSimulation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Product", "Old Target", "New Target", "Old Revenue", "New Revenue", "Impact", "Old Margin ", "New Margin"
            }
        ));
        jScrollPane3.setViewportView(tblRunSimulation);

        jLabel4.setText("Highest Impact Product:");

        jLabel5.setText("Total Revenue Change:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(SuppliersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBelowTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAboveTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(185, 185, 185)
                        .addComponent(btnRunSimulation))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtHighestImpactProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addComponent(txtTotalRevenueChange, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(SuppliersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbBelowTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cmbAboveTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnRunSimulation)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(txtHighestImpactProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txtTotalRevenueChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SuppliersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppliersComboBoxActionPerformed
        // TODO add your handling code here:
        String suppliername = (String) SuppliersComboBox.getSelectedItem();
        populateTable1(suppliername);

    }//GEN-LAST:event_SuppliersComboBoxActionPerformed

    private void SupplierCatalogTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierCatalogTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierCatalogTableMouseEntered

    private void SupplierCatalogTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierCatalogTableMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SupplierCatalogTableMousePressed

    private void btnRunSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunSimulationActionPerformed
        // TODO add your handling code here:
        String belowT = (String) cmbBelowTarget.getSelectedItem();
        String aboveT = (String) cmbAboveTarget.getSelectedItem();
        
        int decreasePercent = Integer.parseInt(belowT.replace("%", ""));
        int increasePercent = Integer.parseInt(aboveT.replace("%", ""));        
        if (selectedsupplier == null) return;       
        ProductCatalog pc = selectedsupplier.getProductCatalog();
        DefaultTableModel model = (DefaultTableModel) tblRunSimulation.getModel();
        model.setRowCount(0);         
        double totalImpact = 0;
        Product highestImpactProduct = null;
        double highestImpact = Double.NEGATIVE_INFINITY;         
        for (Product p : pc.getProductList()) {
            ProductSummary ps = p.getProductSummary();
            int oldTarget = p.getTargetPrice();
            double newTarget = oldTarget;            
            if (ps.getStatus().equals("Below Target")) {
               newTarget = oldTarget * (1 - decreasePercent / 100.0);
            } else if (ps.getStatus().equals("Above Target")) {
               newTarget = oldTarget * (1 + increasePercent / 100.0);
            }
            double oldmargin = p.getOrderPricePerformance();
            p.updateOrderItemPrices(oldTarget/newTarget);
            p.setTargetPrice((int) newTarget);
            double margin = p.getOrderPricePerformance();
            double oldRevenue = ps.getSalesRevenues();
            // percentage change in actual price = the percentage change in target price
            double newRevenue = oldRevenue * (newTarget / oldTarget);
            double impact = newRevenue - oldRevenue;
         
            totalImpact += impact;
            if (impact > highestImpact) {
                highestImpact = impact;
                highestImpactProduct = p;
            }
        
        
            Object[] row = new Object[8];
            row[0] = p;
            row[1] = oldTarget;
            row[2] = (int)newTarget;
            row[3] = (int)oldRevenue;
            row[4] = (int)newRevenue;
            row[5] = (int)impact;
            row[6] = oldmargin;
            row[7] = margin;
            model.addRow(row);
        }
        
        if (highestImpactProduct != null) {
            txtHighestImpactProduct.setText(highestImpactProduct.toString());
        }
        
        txtTotalRevenueChange.setText(String.format("%.2f", totalImpact));

         
    }//GEN-LAST:event_btnRunSimulationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SupplierCatalogTable;
    private javax.swing.JComboBox<String> SuppliersComboBox;
    private javax.swing.JButton btnRunSimulation;
    private javax.swing.JComboBox<String> cmbAboveTarget;
    private javax.swing.JComboBox<String> cmbBelowTarget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblRunSimulation;
    private javax.swing.JTextField txtHighestImpactProduct;
    private javax.swing.JTextField txtTotalRevenueChange;
    // End of variables declaration//GEN-END:variables
private void populateCombobox(){
              SuppliersComboBox.removeAllItems();
              if(business.getSupplierDirectory().getSuplierList()!=null){
                  for(Supplier supplier :business.getSupplierDirectory().getSuplierList()){
                      SuppliersComboBox.addItem(supplier.getName());
                  }
              }
}
}
